### ISSUE TITLE
Error during installation in docker

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems-community/ssl-client#2]
Skipping preload - directory does not exist.
Load started on 06/10/2021 18:40:44
Loading file /opt/irisbuild/module.xml as xml
Imported document: sslclient.ZPM
Load finished successfully.

[sslclient]     Reload START
Skipping preload - directory does not exist.
Load started on 06/10/2021 18:40:45

ERROR #5012: File '/opt/irisbuild/src/community/utils/SSLClient.xml' does not exist
Detected 1 errors during load.

ERROR #5012: File '/opt/irisbuild/src/community/utils/SSLClient.xml' does not exist
[sslclient]     Reload FAILURE - ERROR #5012: File '/opt/irisbuild/src/community/utils/SSLClient.xml' does not exist
ERROR #5012: File '/opt/irisbuild/src/community/utils/SSLClient.xml' does not existThe command '/bin/sh -c iris start IRIS                                         && iris session IRIS < iris.script     && iris stop IRIS quietly' returned a non-zero code: 1
ERROR: Service 'iris' failed to build : Build failed

**Comment by SergeyMi37** [comment]
And when installing in Windows without a docker, there is no error

**Comment by evshvarov** [comment]
fixed. Thanks for mentioning it
